const state={courses:[],completed:new Set(JSON.parse(localStorage.getItem('cyb-plan-completed')||'[]'))};
const $=s=>document.querySelector(s);
const lang={ar:{term:'الفصل',completed:'مكتملة',credits:'ساعة',available:'متاحة الآن',locked:'مقفلة',course:'مادة',done:'مكتملة',needs:'تحتاج',prereq:'متطلب سابق',prereqs:'متطلبات سابقة',noPrereq:'لا توجد متطلبات مسجلة',just:'بداية المشوار',foundation:'تبني أساسك',progress:'تقدم ممتاز',half:'أكثر من منتصف الطريق',final:'المرحلة الأخيرة',complete:'أنجزت الخطة',completedMeta:'مادة مكتملة',reset:'هل تريد إعادة ضبط تقدم جميع المواد؟',noCourses:'لا توجد مواد تطابق الفلاتر.',tryAgain:'جرّب بحثاً أو حالة مختلفة.',unlock:'أكمل مادة من المتطلبات السابقة لفتح الخطوة التالية.',markDone:'تحديد كمكتملة',markRemaining:'تحديد كمتبقية',status:'الحالة',type:'النوع',term:'الفصل',creditsLabel:'الساعات',needed:'مطلوب',courseType:'مادة'},en:{term:'Term',completed:'completed',credits:'credits',available:'Available now',locked:'Locked',course:'Course',done:'Done',needs:'Needs',prereq:'prerequisite',prereqs:'prerequisites',noPrereq:'No prerequisites recorded',just:'Just getting started',foundation:'Building your foundation',progress:'Making good progress',half:'More than halfway there',final:'Final stretch',complete:'Degree complete',completedMeta:'course(s) completed',reset:'Reset all course progress?',noCourses:'No courses match your filters.',tryAgain:'Try a different search or status.',unlock:'Complete a prerequisite course to unlock the next step.',markDone:'Mark as completed',markRemaining:'Mark as remaining',status:'Status',type:'Type',term:'Term',creditsLabel:'Credits',needed:'needed',courseType:'Course'}};
let language=localStorage.getItem('cyb-plan-language')||'ar';
const t=()=>lang[language];
async function init(){const res=await fetch('./data/courses.json');if(!res.ok)throw new Error('Curriculum data could not be loaded');const data=await res.json();state.courses=data.courses||[];populateTerms();render();applyLanguage();}
function populateTerms(){const select=$('#term');select.querySelectorAll('option:not(:first-child)').forEach(o=>o.remove());[...new Set(state.courses.map(c=>c.term))].sort((a,b)=>a-b).forEach(term=>select.insertAdjacentHTML('beforeend',`<option value="${term}">${t().term} ${term}</option>`));}
function save(){localStorage.setItem('cyb-plan-completed',JSON.stringify([...state.completed]));}
function isAvailable(c){return !state.completed.has(c.code)&&(c.prerequisites||[]).every(p=>state.completed.has(p));}
function missingPrereqs(c){return(c.prerequisites||[]).filter(p=>!state.completed.has(p));}
function courseState(c){if(state.completed.has(c.code))return'completed';return isAvailable(c)?'available':'locked';}
function filtered(){const q=$('#search').value.toLowerCase().trim(),term=$('#term').value,status=$('#status').value;return state.courses.filter(c=>{const matchesQ=!q||`${c.code} ${c.name}`.toLowerCase().includes(q),matchesTerm=term==='all'||String(c.term)===term,s=courseState(c),matchesStatus=status==='all'||status===s||(status==='remaining'&&s!=='completed');return matchesQ&&matchesTerm&&matchesStatus;});}
function render(){const courses=filtered(),available=state.courses.filter(isAvailable),total=state.courses.length,completed=state.completed.size,percent=total?Math.round(completed/total*100):0;$('#courseCount').textContent=total;$('#creditCount').textContent=state.courses.reduce((sum,c)=>sum+Number(c.credits||0),0);$('#availableCount').textContent=available.length;$('#progress').textContent=`${percent}%`;$('.progress-ring').style.setProperty('--p',percent);$('#progressMeta').textContent=language==='ar'?`${completed} ${t().completedMeta}`:`${completed} ${t().completedMeta}`;$('#progressLabel').textContent=percent===0?t().just:percent<25?t().foundation:percent<50?t().progress:percent<75?t().half:percent<100?t().final:t().complete;renderAvailable(available);const root=$('#terms');root.innerHTML='';[...new Set(courses.map(c=>c.term))].sort((a,b)=>a-b).forEach(term=>{const list=courses.filter(c=>c.term===term),credits=list.reduce((sum,c)=>sum+Number(c.credits||0),0),done=list.filter(c=>state.completed.has(c.code)).length,section=document.createElement('section');section.className='term';section.innerHTML=`<div class="term-head"><h2>${t().term} ${term}</h2><span>${done}/${list.length} ${t().completed} · ${credits} ${t().credits}</span></div><div class="courses"></div>`;list.forEach(c=>section.querySelector('.courses').appendChild(courseCard(c)));root.appendChild(section);});if(!root.children.length)root.innerHTML=`<div class="empty">${t().noCourses}<br>${t().tryAgain}</div>`;}
function renderAvailable(list){const root=$('#availableCourses');root.innerHTML='';if(!list.length){root.innerHTML=`<div class="next-empty">${t().unlock}</div>`;return;}list.slice(0,8).forEach(c=>{const b=document.createElement('button');b.className='available-card';b.innerHTML=`<span class="availability">${t().available}</span><h3>${escapeHtml(c.code)} · ${escapeHtml(c.name)}</h3><div class="meta"><span>${t().term} ${c.term}</span><span>${c.credits} ${t().credits}</span></div>`;b.addEventListener('click',()=>openCourse(c));root.appendChild(b);});}
function courseCard(c){const s=courseState(c),missing=missingPrereqs(c),b=document.createElement('button');b.className=`course ${s}`;b.setAttribute('aria-label',`${c.code} ${c.name}`);const label=s==='completed'?t().completed:s==='available'?t().available:c.type||t().courseType,action=s==='completed'?`✓ ${t().done}`:s==='available'?t().available:`${t().needs} ${missing.length} ${missing.length===1?t().prereq:t().prereqs}`;b.innerHTML=`<span class="code">${escapeHtml(c.code)}</span><span class="badge">${escapeHtml(label)}</span><h3>${escapeHtml(c.name)}</h3><div class="meta"><span>${c.credits} ${t().credits}</span><span class="status-text ${s}">${escapeHtml(action)}</span></div>`;b.addEventListener('click',()=>openCourse(c));return b;}
function openCourse(c){const prereqs=c.prerequisites||[],missing=missingPrereqs(c),s=courseState(c),prereqHtml=prereqs.length?`<div class="prereq-list">${prereqs.map(p=>`<span class="prereq ${state.completed.has(p)?'':'missing'}">${escapeHtml(p)} ${state.completed.has(p)?'✓':`· ${t().needed}`}</span>`).join('')}</div>`:t().noPrereq;$('#courseDetails').innerHTML=`<div class="detail"><span class="detail-code">${escapeHtml(c.code)}</span><h2>${escapeHtml(c.name)}</h2><div class="detail-row"><strong>${t().term}</strong>${c.term}</div><div class="detail-row"><strong>${t().creditsLabel}</strong>${c.credits}</div><div class="detail-row"><strong>${t().type}</strong>${escapeHtml(c.type||t().courseType)}</div><div class="detail-row"><strong>${t().prereqs}</strong>${prereqHtml}</div><div class="detail-row"><strong>${t().status}</strong>${s==='completed'?t().completed:s==='available'?t().available:`${t().locked} · ${missing.length} ${missing.length===1?t().prereq:t().prereqs} ${t().needed}`}</div><div class="detail-row"><button id="toggleDone" type="button">${s==='completed'?t().markRemaining:t().markDone}</button></div></div>`;$('#toggleDone').onclick=()=>{state.completed.has(c.code)?state.completed.delete(c.code):state.completed.add(c.code);save();$('#courseDialog').close();render();};$('#courseDialog').showModal();}
function applyLanguage(){document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';$('#languageToggle').textContent=language==='ar'?'EN':'عربي';$('#languageToggle').setAttribute('aria-label',language==='ar'?'Switch to English':'التبديل إلى العربية');populateTerms();render();}
function toggleLanguage(){language=language==='ar'?'en':'ar';localStorage.setItem('cyb-plan-language',language);applyLanguage();}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
$('#search').addEventListener('input',render);$('#term').addEventListener('change',render);$('#status').addEventListener('change',render);$('#reset').addEventListener('click',()=>{if(confirm(t().reset)){state.completed.clear();save();render();}});$('#closeDialog').addEventListener('click',()=>$('#courseDialog').close());$('#courseDialog').addEventListener('click',e=>{if(e.target===$('#courseDialog'))$('#courseDialog').close();});$('#languageToggle').addEventListener('click',toggleLanguage);init().catch(err=>{$('#terms').innerHTML=`<div class="empty">${language==='ar'?'تعذر تحميل بيانات الخطة. حاول تحديث الصفحة.':'Could not load curriculum data. Please refresh the page.'}</div>`;console.error(err)});
