const state={courses:[],completed:new Set(JSON.parse(localStorage.getItem('cyb-plan-completed')||'[]'))};
const $=s=>document.querySelector(s);
const lang={ar:{term:'الفصل',completed:'مكتملة',credits:'ساعة',available:'متاحة الآن',locked:'مقفلة',done:'مكتملة',needs:'تحتاج',prereq:'متطلب سابق',just:'بداية المشوار',foundation:'تبني أساسك',progress:'تقدم ممتاز',half:'أكثر من منتصف الطريق',final:'المرحلة الأخيرة',complete:'أنجزت الخطة',completedMeta:'مادة مكتملة',reset:'هل تريد إعادة ضبط تقدم جميع المواد؟',noCourses:'لا توجد مواد تطابق الفلاتر.',tryAgain:'جرّب بحثاً أو حالة مختلفة.',unlock:'أكمل مادة من المتطلبات السابقة لفتح الخطوة التالية.',status:'الحالة',creditsLabel:'الساعات',needed:'مطلوبة',tapDone:'اضغط لإكمالها',tapUndo:'اضغط لإلغاء الإكمال'},en:{term:'Term',completed:'completed',credits:'credits',available:'Available now',locked:'Locked',done:'Done',needs:'Needs',prereq:'prerequisite',just:'Just getting started',foundation:'Building your foundation',progress:'Making good progress',half:'More than halfway there',final:'Final stretch',complete:'Degree complete',completedMeta:'course(s) completed',reset:'Reset all course progress?',noCourses:'No courses match your filters.',tryAgain:'Try a different search or status.',unlock:'Complete a prerequisite course to unlock the next step.',status:'Status',creditsLabel:'Credits',needed:'needed',tapDone:'Tap to complete',tapUndo:'Tap to undo'}};
let language=localStorage.getItem('cyb-plan-language')||'ar';let theme=localStorage.getItem('cyb-plan-theme')||'light';const t=()=>lang[language];const save=()=>localStorage.setItem('cyb-plan-completed',JSON.stringify([...state.completed]));
async function init(){document.documentElement.dataset.theme=theme;updateThemeButton();const res=await fetch('./data/courses.json');state.courses=(await res.json()).courses||[];applyLanguage()}
function populateTerms(){const s=$('#term');s.querySelectorAll('option:not(:first-child)').forEach(o=>o.remove());[...new Set(state.courses.map(c=>c.term))].sort((a,b)=>a-b).forEach(x=>s.insertAdjacentHTML('beforeend',`<option value="${x}">${t().term} ${x}</option>`))}
function isAvailable(c){return !state.completed.has(c.code)&&(c.prerequisites||[]).every(p=>state.completed.has(p))}function missing(c){return(c.prerequisites||[]).filter(p=>!state.completed.has(p))}function status(c){return state.completed.has(c.code)?'completed':isAvailable(c)?'available':'locked'}
function toggleCourse(c){if(status(c)==='locked')return;state.completed.has(c.code)?state.completed.delete(c.code):state.completed.add(c.code);save();render()}
function render(){const q=$('#search').value.toLowerCase().trim(),term=$('#term').value,filter=$('#status').value,courses=state.courses.filter(c=>{const s=status(c);return(!q||`${c.code} ${c.name}`.toLowerCase().includes(q))&&(term==='all'||String(c.term)===term)&&(filter==='all'||filter===s||(filter==='remaining'&&s!=='completed'))}),total=state.courses.length,done=state.completed.size,pct=total?Math.round(done/total*100):0;$('#courseCount').textContent=total;$('#creditCount').textContent=state.courses.reduce((a,c)=>a+Number(c.credits||0),0);$('#availableCount').textContent=state.courses.filter(isAvailable).length;$('#progress').textContent=`${pct}%`;$('.progress-ring').style.setProperty('--p',pct);$('#progressMeta').textContent=`${done} ${t().completedMeta}`;$('#progressLabel').textContent=pct===0?t().just:pct<25?t().foundation:pct<50?t().progress:pct<75?t().half:pct<100?t().final:t().complete;renderAvailable();const root=$('#terms');root.innerHTML='';[...new Set(courses.map(c=>c.term))].sort((a,b)=>a-b).forEach(term=>{const list=courses.filter(c=>c.term===term),sec=document.createElement('section');sec.className='term';sec.innerHTML=`<div class="term-head"><h2>${t().term} ${term}</h2><span>${list.filter(c=>state.completed.has(c.code)).length}/${list.length} ${t().completed}</span></div><div class="courses"></div>`;list.forEach(c=>sec.querySelector('.courses').appendChild(card(c)));root.appendChild(sec)});if(!root.children.length)root.innerHTML=`<div class="empty">${t().noCourses}<br>${t().tryAgain}</div>`}
function renderAvailable(){const root=$('#availableCourses');root.innerHTML='';const list=state.courses.filter(isAvailable);if(!list.length){root.innerHTML=`<div class="next-empty">${t().unlock}</div>`;return}list.slice(0,8).forEach(c=>{const b=document.createElement('button');b.className='available-card';b.innerHTML=`<span class="availability">${t().available}</span><h3>${escapeHtml(c.code)} · ${escapeHtml(c.name)}</h3><div class="meta"><span>${t().term} ${c.term}</span><span>${c.credits} ${t().credits}</span></div>`;b.onclick=()=>toggleCourse(c);root.appendChild(b)})}
function card(c){const s=status(c),b=document.createElement('button');b.className=`course ${s}`;b.disabled=s==='locked';b.setAttribute('aria-label',`${c.code} ${c.name}`);b.innerHTML=`<span class="code">${escapeHtml(c.code)}</span><span class="badge">${s==='completed'?`✓ ${t().completed}`:s==='available'?t().available:t().locked}</span><h3>${escapeHtml(c.name)}</h3><div class="meta"><span>${c.credits} ${t().credits}</span><span class="status-text ${s}">${s==='completed'?`✓ ${t().tapUndo}`:s==='available'?`+ ${t().tapDone}`:`${t().needs} ${missing(c).length} ${t().prereq}`}</span></div>`;b.onclick=()=>toggleCourse(c);return b}
function applyLanguage(){document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';$('#languageToggle').textContent=language==='ar'?'EN':'عربي';populateTerms();render()}function toggleLanguage(){language=language==='ar'?'en':'ar';localStorage.setItem('cyb-plan-language',language);applyLanguage()}function toggleTheme(){theme=theme==='dark'?'light':'dark';localStorage.setItem('cyb-plan-theme',theme);document.documentElement.dataset.theme=theme;updateThemeButton()}function updateThemeButton(){$('#themeToggle').textContent=theme==='dark'?'☀':'☾'}function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#search').oninput=render;$('#term').onchange=render;$('#status').onchange=render;$('#reset').onclick=()=>{if(confirm(t().reset)){state.completed.clear();save();render()}};$('#languageToggle').onclick=toggleLanguage;$('#themeToggle').onclick=toggleTheme;init().catch(console.error);