const state={courses:[],completed:new Set(JSON.parse(localStorage.getItem('cyb-plan-completed')||'[]'))};
const $=s=>document.querySelector(s);
async function init(){const res=await fetch('data/courses.json');if(!res.ok)throw new Error('Curriculum data could not be loaded');const data=await res.json();state.courses=data.courses||[];[...new Set(state.courses.map(c=>c.term))].sort((a,b)=>a-b).forEach(term=>$('#term').insertAdjacentHTML('beforeend',`<option value="${term}">Term ${term}</option>`));render();}
function save(){localStorage.setItem('cyb-plan-completed',JSON.stringify([...state.completed]));}
function isAvailable(c){return !state.completed.has(c.code)&&(c.prerequisites||[]).every(p=>state.completed.has(p));}
function missingPrereqs(c){return(c.prerequisites||[]).filter(p=>!state.completed.has(p));}
function courseState(c){if(state.completed.has(c.code))return'completed';return isAvailable(c)?'available':'locked';}
function filtered(){const q=$('#search').value.toLowerCase().trim(),term=$('#term').value,status=$('#status').value;return state.courses.filter(c=>{const matchesQ=!q||`${c.code} ${c.name}`.toLowerCase().includes(q),matchesTerm=term==='all'||String(c.term)===term,s=courseState(c),matchesStatus=status==='all'||status===s||(status==='remaining'&&s!=='completed');return matchesQ&&matchesTerm&&matchesStatus;});}
function render(){const courses=filtered(),available=state.courses.filter(isAvailable),total=state.courses.length,completed=state.completed.size,percent=total?Math.round(completed/total*100):0;$('#courseCount').textContent=total;$('#creditCount').textContent=state.courses.reduce((sum,c)=>sum+Number(c.credits||0),0);$('#availableCount').textContent=available.length;$('#progress').textContent=`${percent}%`;$('.progress-ring').style.setProperty('--p',percent);$('#progressMeta').textContent=`${completed} course${completed===1?'':'s'} completed`;$('#progressLabel').textContent=percent===0?'Just getting started':percent<25?'Building your foundation':percent<50?'Making good progress':percent<75?'More than halfway there':percent<100?'Final stretch':'Degree complete';renderAvailable(available);const root=$('#terms');root.innerHTML='';[...new Set(courses.map(c=>c.term))].sort((a,b)=>a-b).forEach(term=>{const list=courses.filter(c=>c.term===term),credits=list.reduce((sum,c)=>sum+Number(c.credits||0),0),done=list.filter(c=>state.completed.has(c.code)).length,section=document.createElement('section');section.className='term';section.innerHTML=`<div class="term-head"><h2>Term ${term}</h2><span>${done}/${list.length} completed · ${credits} credits</span></div><div class="courses"></div>`;list.forEach(c=>section.querySelector('.courses').appendChild(courseCard(c)));root.appendChild(section);});if(!root.children.length)root.innerHTML='<div class="empty">No courses match your filters.<br>Try a different search or status.</div>';}
function renderAvailable(list){const root=$('#availableCourses');root.innerHTML='';if(!list.length){root.innerHTML='<div class="next-empty">No new courses are unlocked yet. Complete a prerequisite course to unlock the next step.</div>';return;}list.slice(0,8).forEach(c=>{const b=document.createElement('button');b.className='available-card';b.innerHTML=`<span class="availability">Available now</span><h3>${escapeHtml(c.code)} · ${escapeHtml(c.name)}</h3><div class="meta"><span>Term ${c.term}</span><span>${c.credits} credits</span></div>`;b.addEventListener('click',()=>openCourse(c));root.appendChild(b);});}
function courseCard(c){const s=courseState(c),missing=missingPrereqs(c),b=document.createElement('button');b.className=`course ${s}`;b.setAttribute('aria-label',`${c.code} ${c.name}`);const label=s==='completed'?'COMPLETED':s==='available'?'AVAILABLE':c.type||'COURSE',action=s==='completed'?'✓ Done':s==='available'?'Available now':`Needs ${missing.length} prereq${missing.length===1?'':'s'}`;b.innerHTML=`<span class="code">${escapeHtml(c.code)}</span><span class="badge">${escapeHtml(label)}</span><h3>${escapeHtml(c.name)}</h3><div class="meta"><span>${c.credits} credit${Number(c.credits)===1?'':'s'}</span><span class="status-text ${s}">${escapeHtml(action)}</span></div>`;b.addEventListener('click',()=>openCourse(c));return b;}
function openCourse(c){const prereqs=c.prerequisites||[],missing=missingPrereqs(c),s=courseState(c),prereqHtml=prereqs.length?`<div class="prereq-list">${prereqs.map(p=>`<span class="prereq ${state.completed.has(p)?'':'missing'}">${escapeHtml(p)} ${state.completed.has(p)?'✓':'· needed'}</span>`).join('')}</div>`:'No prerequisites recorded';$('#courseDetails').innerHTML=`<div class="detail"><span class="detail-code">${escapeHtml(c.code)}</span><h2>${escapeHtml(c.name)}</h2><div class="detail-row"><strong>Term</strong>${c.term}</div><div class="detail-row"><strong>Credits</strong>${c.credits}</div><div class="detail-row"><strong>Type</strong>${escapeHtml(c.type||'Course')}</div><div class="detail-row"><strong>Prerequisites</strong>${prereqHtml}</div><div class="detail-row"><strong>Status</strong>${s==='completed'?'Completed':s==='available'?'Available now':`Locked · ${missing.length} prerequisite${missing.length===1?'':'s'} remaining`}</div><div class="detail-row"><button id="toggleDone" type="button">${s==='completed'?'Mark as remaining':'Mark as completed'}</button></div></div>`;$('#toggleDone').onclick=()=>{state.completed.has(c.code)?state.completed.delete(c.code):state.completed.add(c.code);save();$('#courseDialog').close();render();};$('#courseDialog').showModal();}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
$('#search').addEventListener('input',render);$('#term').addEventListener('change',render);$('#status').addEventListener('change',render);$('#reset').addEventListener('click',()=>{if(confirm('Reset all course progress?')){state.completed.clear();save();render();}});$('#closeDialog').addEventListener('click',()=>$('#courseDialog').close());$('#courseDialog').addEventListener('click',e=>{if(e.target===$('#courseDialog'))$('#courseDialog').close();});init().catch(err=>{$('#terms').innerHTML='<div class="empty">Could not load curriculum data. Please try refreshing the page.</div>';console.error(err)});
